### ISSUE TITLE
Document steps to provide own scraper

### ISSUE THREAD

**Issue by pwalsh** [opentrials/scraper#5]
# Description

We'd love rd parties to help us acquire data! Let's make that easier with a step-by-step guide to writing your own scraper, which can be merged with the core scrapers and run to populate the Warehouse.

# Tasks

* [ ] Document as Markdown in repo, linked from README, with explicit steps to write a scraper for the OpenTrials platform, from zero to PR with scraper

**Comment by roll** [comment]
DONE
